Controllers/DeptController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace hmsAdmin.Controllers
{
    public class DeptController : Controller
    {
        // Make a refrence from HmsContext
        private readonly HmsContext _db;

        //Make a constructor to connect with HmsContext
        public DeptController(HmsContext db)
        {
            _db = db; // have Full Access To DB 
        }

        public IActionResult Index()
        {
            int drCnt = 0, nsCnt = 0;
            var depts = _db.Departments.FromSql($"SELECT * FROM departments");
            Dictionary<int, int> dr = new Dictionary<int, int>();
            Dictionary<int, int> ns = new Dictionary<int, int>();
            foreach (var d in depts)
            {
                drCnt = 0;
                nsCnt = 0;
                var drQ = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE fk_dept = {d.Id}");
                foreach(var c in drQ)
                {
                    drCnt++;
                }
                dr.Add(d.Id, drCnt);
                var nsQ = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE fk_dept = {d.Id}");
                foreach (var c in nsQ)
                {
                    nsCnt++;
                }
                ns.Add(d.Id, nsCnt);
            }

            ViewBag.Doc = dr;
            ViewBag.Nur = ns;

            IEnumerable<Department> deptData = _db.Departments.ToList();
            return View(deptData);
        }


        // -- Create --
        // GET
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department obj, IFormFile deptImage)
        {
            // Check Image
            if (deptImage == null)
                ModelState.AddModelError("Image", "Please, Select an Image!");

            // Check The Name
            var name = _db.Departments.FromSql($"SELECT * FROM departments WHERE name = {obj.Name}");
            foreach (var p in name)
            {
                if (p.Name == null)
                    break;
                else
                {
                    ModelState.AddModelError("Name", "This Name is already exist!!");
                    break;
                }
            }

            if (ModelState.IsValid)
            {
                _db.Departments.Add(obj);
                _db.SaveChanges();

                // Upload The Image
                try
                {
                    // Upload The Image To wwwroot Folder
                    string imageName = deptImage.FileName;
                    imageName = $"{obj.Id}-" + Path.GetFileName(imageName);
                    string uploadFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/dept", imageName);
                    var stream = new FileStream(uploadFilePath, FileMode.Create);
                    deptImage.CopyToAsync(stream);
                    // Using SQL Queries To Update The Image 
                    using (var trans = _db.Database.BeginTransaction())
                    {
                        _db.Database.ExecuteSqlInterpolated($"UPDATE departments SET image = {imageName} WHERE id = {obj.Id}");
                        _db.SaveChanges();
                        trans.Commit();
                    }
                }
                catch (Exception e)
                {
                    TempData["error"] = "Oops, Errors Occured!";
                    return View(obj);
                }

                TempData["success"] = "Department Created Successfully!";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Oops, Errors Occured!";
            return View(obj);
        }

        // -- Update --
        // GET
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Departments.Find(id);
            if (obj == null)
                return NotFound();

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Department obj)
        {
			// Check The Name
			var name = _db.Departments.FromSql($"SELECT * FROM departments WHERE name = {obj.Name} AND id != {obj.Id}");
			foreach (var p in name)
			{
				if (p.Name == null)
					break;
				else
				{
					ModelState.AddModelError("Name", "This Name is already exist!!");
					break;
				}
			}

			if (ModelState.IsValid)
            {
                _db.Departments.Update(obj);
                _db.SaveChanges();

				TempData["success"] = "Department Updated Successfully!";
				return RedirectToAction("Index");
            }
			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Image --
        // GET
        [HttpGet]
        public IActionResult EditImage(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Departments.Find(id);
            if (obj == null)
                return NotFound();

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditImage(Department obj, IFormFile deptImage)
        {
            // Check Image
            if (deptImage == null)
                ModelState.AddModelError("Image", "Please, Select an Image!");

            if (ModelState.IsValid)
            {
                _db.Departments.Update(obj);
                _db.SaveChanges();

                // Update The Image if the user choose to change his image
                try
                {
                    // Upload The Image To wwwroot Folder
                    string imageName = deptImage.FileName;
                    imageName = $"{obj.Id}-" + Path.GetFileName(imageName);
                    string uploadFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/dept", imageName);
                    var stream = new FileStream(uploadFilePath, FileMode.Create);
                    deptImage.CopyToAsync(stream);
                    // Using SQL Queries To Update The Image 
                    using (var trans = _db.Database.BeginTransaction())
                    {
                        _db.Database.ExecuteSqlInterpolated($"UPDATE departments SET image = {imageName} WHERE id = {obj.Id}");
                        _db.SaveChanges();
                        trans.Commit();
                    }
                }
                catch (Exception e)
                {
                    TempData["error"] = "Oops, Errors Occured!";
                    return View(obj);
                }

                TempData["success"] = "Image Updated Successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Oops, Errors Occured!";
            return View(obj);
        }

        // -- Delete --
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Departments.Find(id);
            if (obj == null)
                return NotFound();

            // FIRST, Delete All Children of The Depatment 
            var drIds = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE fk_dept = {id}");
            foreach (var dr in drIds)
            {
                _db.Database.ExecuteSqlInterpolated($"DELETE FROM doctors WHERE id = {dr.Id}");
                _db.SaveChanges();
            }
            var nsIds = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE fk_dept = {id}");
            foreach (var ns in nsIds)
            {
                _db.Database.ExecuteSqlInterpolated($"DELETE FROM nurses WHERE id = {ns.Id}");
                _db.SaveChanges();
            }
            var appIds = _db.Appointments.FromSql($"SELECT * FROM appointments WHERE departmentid = {id}");
            foreach (var app in appIds)
            {
                _db.Database.ExecuteSqlInterpolated($"DELETE FROM appointments WHERE id = {app.Id}");
                _db.SaveChanges();
            }


            // DELETE The Parent
            _db.Database.ExecuteSqlInterpolated($"DELETE FROM departments WHERE id = {id}");
            _db.SaveChanges();

            TempData["success"] = "Department Deleted Successfully!";
			return RedirectToAction("Index");
        }

        // Our Departments
        [HttpGet]
        public IActionResult Department()
        {
            IEnumerable<Department> deptData = _db.Departments.ToList();
            return View(deptData);
        }
        // Show a single department
        [HttpGet]
        public IActionResult SingleDepartment(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Departments.Find(id);
            if (obj == null)
                return NotFound();

            // Department Details
            var deptData = _db.Departments.FromSql($"SELECT * FROM departments WHERE id = {id}");
            deptData.ToList();
            ViewBag.Dept = deptData;
            
            foreach(var dept in deptData)
            {
                ViewBag.Name = dept.Name;
                break;
            }

            // Stuff Details
            int drCnt = 0, nsCnt = 0;
            var depts = _db.Departments.FromSql($"SELECT * FROM departments WHERE id  = {id}");
            Dictionary<int, int> dr = new Dictionary<int, int>();
            Dictionary<int, int> ns = new Dictionary<int, int>();
            foreach (var d in depts)
            {
                var drQ = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE fk_dept = {d.Id}");

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Hospital Care - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.css"/>    
    
    <!-- Basic Page Needs
      ================================================== -->
        <meta charset="utf-8" />

        <link rel="icon" href="~/theme/images/favicon.ico" type="image/icon type" />
    
        <!--
      Essential stylesheets
      =====================================-->
        <link rel="stylesheet" href="~/theme/plugins/bootstrap/bootstrap.min.css" />
        <link rel="stylesheet" href="~/theme/plugins/icofont/icofont.min.css" />
        <link rel="stylesheet" href="~/theme/plugins/slick-carousel/slick/slick.css" />
        <link
          rel="stylesheet"
          href="~/theme/plugins/slick-carousel/slick/slick-theme.css"
        />
    
        <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/theme/css/style.css" />
    
    @await RenderSectionAsync("style", required: false)
</head>
<body>

<header>
  <div class="header-top-bar">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
        
        </div>
        <div class="col-lg-6">
          <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
            <partial name="_LoginPartial" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navigation" id="navbar">
    <div class="container">
      <a class="navbar-brand" asp-controller="Home" asp-action="Index">
        <img src="~/theme/images/favicon.png" alt="" class="img-fluid" />
      </a>

      <button
        class="navbar-toggler collapsed"
        type="button"
        data-toggle="collapse"
        data-target="#navbarmain"
        aria-controls="navbarmain"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="icofont-navigation-menu"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarmain">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Services">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Dept" asp-action="Department">Departments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Doctor" asp-action="Doctors">Doctors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

@RenderBody()

<!-- footer Start -->
<footer class="footer section">
  <div class="container">
    <div class="footer-btm py-4 mt-2">
      <div class="row align-items-center justify-content-between">
        <div class="col-lg-12">
          <div class="copyright text-center">
            Copyright &copy; 2024
             <a href="#top">Before Others</a>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4">
          <a class="backtop scroll-top-to" href="#top">
            <i class="icofont-long-arrow-up"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

<script src="~/theme/plugins/jquery/jquery.js"></script>
<script src="~/theme/plugins/bootstrap/bootstrap.min.js"></script>
<script src="~/theme/plugins/slick-carousel/slick/slick.min.js"></script>
<script src="~/theme/plugins/shuffle/shuffle.min.js"></script>

<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA"></script>
<script src="~/theme/plugins/google-map/gmap.js"></script>

<script src="~/theme/js/script.js"></script>
@* *@
@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
@* <script src="~/js/site.js" asp-append-version="true"></script> *@
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutDoctor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CareCoord - @ViewData["Title"]</title>
   
    <link rel="stylesheet" href="~/Doctor/lib/bootstrap/bootstrap.min.css" />
    <link rel="icon" href="~/theme/images/favicon.ico" type="image/icon type" />
  
    <link rel="stylesheet" href="~/Doctor/css/style.css" />
    <link rel="stylesheet" href="~/Doctor/css/style.css.map" />
    <link rel="stylesheet" href="~/theme/css/style.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

    @RenderBody()


    <!-- footer Start -->
    <footer class="footer section">
        <div class="container">
            <div class="footer-btm py-4 mt-2">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-12">
                        <div class="copyright text-center">
                            Copyright &copy; 2023
                            <a href="#top">Before Others</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/Doctor/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Doctor/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Nurse_ayman.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CareCoord - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/Nurse_ayman.css" asp-append-version="true"/>
    <!-- Font Awesome -->
    @*<link rel="stylesheet"
            href="~/dist/css/icons/font-awesome/css/fa-brands.min.css" />
    <link rel="stylesheet"
            href="~/dist/css/icons/font-awesome/css/fa-regular.min.css" />
    <link rel="stylesheet"
            href="~/dist/css/icons/font-awesome/css/fa-solid.min.css" />
    <link rel="stylesheet"
            href="~/dist/css/icons/font-awesome/css/fontawesome-all.min.css" />
    <link rel="stylesheet"
            href="~/dist/css/icons/font-awesome/css/all.min.css" />*@
    <!-- font awesome Stylesheet -->
    <link href="~/fontawesome-free-6.4.0-web/css/fontawesome.min.css" rel="stylesheet">
     <link href="~/fontawesome-free-6.4.0-web/css/brands.css" rel="stylesheet">
    <link href="~/fontawesome-free-6.4.0-web/css/solid.css" rel="stylesheet">
    <link rel="icon" href="~/theme/images/favicon.ico" type="image/icon type" />
    <link rel="stylesheet" href="~/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/theme/plugins/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="~/theme/plugins/icofont/icofont.min.css" />
    <link rel="stylesheet" href="~/theme/plugins/slick-carousel/slick/slick.css" />
            <link
              rel="stylesheet"
              href="~/theme/plugins/slick-carousel/slick/slick-theme.css"
            />
        
            <!-- Main Stylesheet -->
        <link rel="stylesheet" href="~/theme/css/style.css" />
</head>
<body>

@RenderBody()

    <!-- footer Start -->
    <footer class="footer section">
        <div class="container">
            <div class="footer-btm py-4 mt-2">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-12">
                        <div class="copyright text-center">
                            Copyright &copy; 2023
                            <a href="#top">Before Others</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

@await RenderSectionAsync("Scripts", required:false)

</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]')
	</script>
}
@if (TempData["error"] != null)
{
	<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]')
	</script>
}
@if (TempData["warning"] != null)
{
	<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.warning('@TempData["warning"]')
	</script>
}