Controllers/Nurse_aymanController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;


namespace HMS.Controllers;

public class Nurse_aymanController : Controller
{
    public Nurse_aymanController(HmsContext db)
    {
        _db = db;
    }
        
    private readonly HmsContext _db;
    // GET
    public IActionResult Index(int id)
    {
        using (var connection = new SqlConnection("Data Source=.;Initial Catalog=HMS;Integrated Security=True;Encrypt=False;Trust Server Certificate=True"))
        {
            connection.Open();

            var command = new SqlCommand("SELECT COUNT(*) FROM Cash_Flows", connection);
            var result = (int)command.ExecuteScalar();

            if (result == 0)
            {
                // Create a new record in the Cash_Flows table
                var insertCommand = new SqlCommand("INSERT INTO Cash_Flows (Appointments_Cash, Lab_Cash, Pharmacy_Cash) VALUES (0, 0, 0)", connection);
                insertCommand.ExecuteNonQuery();
            }
        }
        
        
        var nurse = _db.Nurses.FirstOrDefault(d => d.Id == id);
        return View(nurse);
    }
    
    public IActionResult Nurse_profile(int id)
    {
        var nurse = _db.Nurses.FirstOrDefault(d => d.Id == id);
        return View(nurse);
    }

    
    public IActionResult Nurse_search(int id)
    {
        
        IEnumerable<Appointment> patientList = _db.Appointments
            .Include(n=>n.Patient)
            .Include(d=>d.Department)
            .ToList();
        ViewBag.ID = id;
        // .Include(a => a.FkPat).ToList()
        return View(patientList);
    }
    
    [HttpPost]
    public IActionResult Nurse_search_post(int id)
        {
            var update = _db.Appointments
                .Include(n=>n.Patient)
                .Include(d=>d.Department)
                .FirstOrDefault(x => x.Id == id);
            if (update == null) return NotFound();
            update.Status = 1;
            
            var cash = _db.Cash_Flows.FirstOrDefault();
            cash.appointments_cash += 50;
            _db.Cash_Flows.Update(cash);
            _db.Update(update);
            _db.SaveChanges();
    
            return RedirectToAction();
        }
    
    [HttpPost]
    public IActionResult Search(string SSN )
    {
        var patient = _db.AspNetUsers.FirstOrDefault(p => p.SSN == SSN);
        if (patient == null)
        {
            var model = new Appointment()
                { PatientID = "No Result" };
            return View(model);
        }

        var appointment = _db.Appointments
            .Include(n=>n.Patient)
            .Include(d=>d.Department)
            .FirstOrDefault(a => a.PatientID == patient.Id);
        var _model = appointment;
        if (_model == null)
        {
            var model = new Appointment()
                { PatientID = "No Result" };
            return View(model);
        }
        
        var viewModel = new Appointment()
        {
            PatientID = patient.Name,
            Department = appointment.Department ,
            Day = appointment.Day,
            Status = appointment.Status,
            Id = appointment.Id
        };
         

        return View("Search", viewModel );
    }
    
    
    public IActionResult Nurse_Pharmacy(int id)
    {
        ViewBag.ID = id;
        return View();
    }
    
    [HttpPost]
    public IActionResult Nurse_Pharmacy(string SSN )
    {
        if (string.IsNullOrEmpty(SSN)){ return View();}
        var patient = _db.AspNetUsers.FirstOrDefault(p => p.SSN == SSN);
        if (patient == null) {return View();}
       
        var appointments = _db.Appointments.Where(a => a.PatientID == patient.Id).ToList();
        if (appointments == null || appointments.Count==0) {return View();}

        var diagnoses = new List<Diagnose>() { };

        foreach (var app in appointments)
          {
             diagnoses.AddRange(_db.Diagnose.
                  Include(d => d.Appointments).
                  ThenInclude(o => o.Patient).
                  Include(dep => dep.Appointments).
                  ThenInclude(n => n.Department).
                  Where(d => d.fk_app == app.Id).ToList());
          }
          if (diagnoses == null || diagnoses.Count==0) {return View();}
        return View(diagnoses);
    }
    
    [HttpPost]
    public IActionResult Pharmacy_update()
    {

        var cash = _db.Cash_Flows.FirstOrDefault();
        cash.Pharmacy_cash += 19;
        _db.Cash_Flows.Update(cash);
        _db.SaveChanges();
        //TempData["Success"] = "Data updated successfully";

        return RedirectToAction("Nurse_Pharmacy");
    }
    
    public IActionResult Nurse_Lab(int id)
    {
        ViewBag.ID = id;
        return View();
    }
    
    [HttpPost]
    public IActionResult Nurse_Lab(string SSN )
    {
        if (string.IsNullOrEmpty(SSN)) return View();
        var patient = _db.AspNetUsers.FirstOrDefault(p => p.SSN == SSN);
        if (patient == null) {return View();}
        var appointment = _db.Appointments.FirstOrDefault(a => a.PatientID == patient.Id);
        if (appointment == null) {return View();}
        var analysis = _db.Labs.FirstOrDefault(L => L.FkApp == appointment.Id);
        if (analysis == null) {return View();}
        
        var analysis_ = _db.Labs.
            Include(d => d.Appointments).
            ThenInclude(z => z.Patient).
            Include(dep => dep.Appointments).
            ThenInclude(n => n.Department).
            FirstOrDefault(d => d.FkApp == appointment.Id);

        return View(analysis_);
    }
    
    [HttpPost]
    public IActionResult Lab_update(int? id, string result, int? SSN)
    {
        var update = _db.Labs.FirstOrDefault(x => x.Id == id);
        var cash = _db.Cash_Flows.FirstOrDefault();
        cash.Lab_cash += 50;
        if (update == null) return NotFound();
        update.Result = result ;
        _db.Labs.Update(update);
        _db.Cash_Flows.Update(cash);
        _db.SaveChanges();
        //TempData["Success"] = "Data updated successfully";
    
        return RedirectToAction("Nurse_Lab", new {SSN = SSN});
    }
    
    public IActionResult Nurse_Cash_Flow(int id)
    {
        ViewBag.ID = id ;
        var money = _db.Cash_Flows.FirstOrDefault();
        return View(money);
    }
    
    public IActionResult Nurse_Book()
    {
        return View();
    }
    
    public IActionResult Nurse_add_new()
    {
        return View();
    }
    



}

Controllers/SearchController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Controllers


{
    public class SearchController : Controller
    {


        public SearchController(HmsContext db)
        {
            _db = db;
        }

        private readonly HmsContext _db;




        /*-------------------------------------------------------------------------*/
        public IActionResult Spatient(string? nid)
        {
            if (nid == null)
            {
                var patients = _db.AspNetUsers
                    .Include(p => p.Appointments)
                    .ToList();

                return View(patients);
            }
            else
            {
                var patient = _db.AspNetUsers
                    .Include(p => p.Appointments)
                    .FirstOrDefault(p => p.SSN == nid);

                if (patient == null)
                {
                    return NotFound("No Patient");
                }

                return View(new List<Patient> { patient });
            }
        }









        /*-------------------------------------------------------------------------*/

        public IActionResult Shictory(string? Id)
        {
            if (Id == null)
            {
                return NotFound("Not Found");
            }


            var patient = _db.AspNetUsers.Find(Id);
            var appointment = _db.Appointments.FirstOrDefault(a => a.PatientID == patient.Id);

      

            var diagnosis = _db.Diagnose.Where(d => d.fk_app == appointment.Id).ToList();

        
           
            return View(diagnosis);
        }








        /*-------------------------------------------------------------------------*/




        //public IActionResult edit(string? Id)
        //{
        //    // Get the current patient
        //    var patient = _db.AspNetUsers.Find(Id);

        //    // Get the current prescription for the patient
        //    var appointment = _db.Appointments.FirstOrDefault(g => g.PatientID==  patient.Id);
        //    var diagnosis = _db.Diagnoses.Where(d => d.FkApp == appointment.Id).ToList();

        //    // Pass the prescription data to the view
        //    return View(diagnosis);
        //}



        ////Post
        //[HttpPost]
        //[ValidateAntiForgeryToken]


        //public IActionResult edit(Diagnose model)
        //{
        //    // Get the diagnosis from the database
        //    var diagnosis = _db.Diagnoses.Find(model.Id);
        //    if (diagnosis != null)
        //    {

        //        // Update the diagnosis with the new data
        //        diagnosis.Prescription = model.Prescription;
        //        diagnosis.Description = model.Description;
        //        diagnosis.Analysis = model.Analysis;
        //        diagnosis.FkApp = model.FkApp;

        //        _db.SaveChanges();

        //        // Redirect to the Hictory page
        //        var appointment = _db.Appointments.FirstOrDefault(a => a.Id == diagnosis.FkApp);
        //        return RedirectToAction("Hictory", new { id = appointment.PatientID });
        //    }
        //    else { return NotFound("Not found"); }

        //}

        public IActionResult Edit(int? id)
        {
            var diagnosis = _db.Diagnose.Find(id);
            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        [HttpPost]
        public IActionResult Edit(int id, Diagnose model)
        {
            var diagnosis = _db.Diagnose.Find(id);
            if (diagnosis == null)
            {
                return NotFound();
            }

            diagnosis.Prescription = model.Prescription;
            diagnosis.Description = model.Description;
            diagnosis.Analysis = model.Analysis;

            _db.SaveChanges();
            TempData["sure"] = "The Data has been updated successfully";

            return RedirectToAction("Spatient");
        }



        /*-------------------------------------------------------------------------*/


        public IActionResult Delete(int? Id)
        {
            if (Id == null )
            {
                return NotFound();
            }
            var del = _db.Diagnose.Find(Id);
            if (del == null)
            {
                return NotFound();
            }
            return View(del);
        }



        //Post
        [HttpPost]

        public IActionResult Delete(Diagnose k,string? Id)
        {

            _db.Diagnose.Remove(k);
            _db.SaveChanges();
            TempData["sure"] = "The Data has been delete successfully";
            return RedirectToAction("Spatient");
            
          
        }






    }
}

Views/Nurse_ayman/Index.cshtml
@model Nurse

@{
  ViewBag.Title = "Nurse";
  Layout = "_Layout_Nurse_ayman";
}
@if (Model != null)
{
    <title>Nurse</title>

    <section class="a-page-title bg-1"> 
          <div class="overlay"></div>
            <div class="column-md">
              <div class="text-center">
                <h1 class="text-capitalize">Hospital Management System</h1>
                <ul class="line-in-list">
                  <li class="nurse-list"><a asp-controller="Home" asp-action="Index" class="except"> Home</a></li>
                  <li class="nurse-list">/</li>
                  <li class="nurse-list">Nurse</li>
                </ul>
              </div>
            </div>
        </section>

    <section class="Nurse-section">
    
    
            <a asp-controller="Nurse_ayman" asp-action="Nurse_profile" asp-route-id="@Model.Id" class="nurse-link" >
                <div class="nurse-card">
                    <i  class="nurse-fontawesome fa-solid fa-user-nurse fa-7x" style="right:30.4%;"></i> 
                    <p style="position: absolute; top: 50%;left: 33%;"> MY Profile</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Show and edit your personal data, Update your image</p>
                </div> 
            </a>

        <a asp-controller="Nurse_ayman" asp-action="Nurse_search" asp-route-id="@Model.Id" class="nurse-link">

            <div class="nurse-card">
                    <i  class="fa-regular fa-magnifying-glass fa-7x nurse-fontawesome" style="right:27.6%;"></i> 
                    <p style="position: absolute; top: 50%;left: 20%;"> Find an appointment</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Find an appointment by the patient's National-ID .. and Check payment status </p>
                </div> 

            </a>

            <a target="_blank" asp-controller="Home" asp-action="Index" class="nurse-link">

                <div class="nurse-card">
                    <i  class="fas fa-plus fa-7x nurse-fontawesome" style="right:30.4%;"></i> 
                    <p style="position: absolute; top: 50%;left: 33%;"> New Patient</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Recording patient data for the first time</p>
                </div> 

            </a>

            <a target="_blank" asp-controller="Home" asp-action="Index" class="nurse-link">

                <div class="nurse-card">
                    <i   class="fa-solid fa-calendar-plus fa-7x nurse-fontawesome" style="right:27.6%;"></i> 
                    <p style="position: absolute; top: 50%;left: 25%;"> New Appointment</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Book an appointment for a patient whose data is registered on the system</p>
                </div>

            </a>

        <a asp-controller="Nurse_ayman" asp-action="Nurse_Pharmacy" asp-route-id="@Model.Id" class="nurse-link">

                <div class="nurse-card">
                    <i class="fa-solid fa-pills fa-7x nurse-fontawesome" style="display: block; position: absolute; top: 3%; right:24.8%;"></i> 
                    <p style="position: absolute; top: 50%;left: 33%;"> Pharmacy</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Dispensing the medication to the patient who has finished the visit</p>
                </div>

            </a>

        <a asp-controller="Nurse_ayman" asp-action="Nurse_Lab" asp-route-id="@Model.Id" class="nurse-link">

                <div class="nurse-card">
                    <i class="fa-solid fa-vials fa-7x nurse-fontawesome" style="right:27.6%;"></i>
                    <p style="position: absolute; top: 50%;left: 43%;"> Lab</p>
                    <p style="position: absolute; top: 66%;left: 3%;" > Medical analyzes & Examinations</p>
                </div> 

            </a>

            <a asp-controller="Nurse_ayman" asp-action="Nurse_Cash_Flow" asp-route-id="@Model.Id" class="nurse-link">

                <div class="nurse-card">
                    <i class="fa-solid fa-square-poll-vertical fa-7x  nurse-fontawesome" style="right:30.7%;"></i> 
                    <p style="position: absolute; top: 50%;left: 33%;"> Money Flow</p>
                    <p style="position: absolute; top: 66%;left: 11%;" > Your daily financial statistics</p>
                </div> 

            </a>

            <a asp-controller="Home" asp-action="Index" class="nurse-link">

            <div class="nurse-card">
              <i class="fa-solid fa-right-from-bracket fa-7x nurse-fontawesome" style="right:27.6%;"></i> 
              <p style="position: absolute; top: 50%;left: 37%; justify-content: center; "> Log Out</p>
              <p style="position: absolute; top: 66%;left: 13%;" > Log out and go home Page</p>
            </div>

            </a>
    

        </section>

}
else
{
    <h1 align="center" class="mt-5">NOT FOUND 404 :(</h1>
}
    

Views/Nurse_ayman/Nurse_Book.cshtml
@model dynamic

@{
    ViewBag.Title = "Book  New Appointment";
    Layout = "_Layout_Nurse_ayman";
}


<section class="a-page-title bg-1"> 
      <div class="overlay"></div>
        <div class="column-md">
          <div class="text-center">
            <h1 class="text-capitalize">Hospital Management System</h1>
            <ul class="line-in-list">
              <li class="nurse-list"><a asp-controller="Nurse_ayman" asp-action="Index" class="except"> Nurse</a></li>
              <li class="nurse-list">/</li>
              <li class="nurse-list">Nurse - Book an Appoinment</li>
            </ul>
          </div>
        </div>
    </section>

  <section class="Nurse-Book-section"> 

    <div class="date-box" id="date-box" disabled>
        <div class="date-item">
          <div class="date-item-label">Day</div>
          <div id="day"></div>
        </div>
        <div class="date-item">
          <div class="date-item-label">Date</div>
          <div id="date"></div>
        </div>
        <div class="date-item">
          <div class="date-item-label">Time</div>
          <div id="time"></div>
        </div>
    </div>

    <section class="appoinment section">
        <div class="container">
          <div class="row">
            <div class="col-lg-4">
                <div class="mt-3">
                  <div class="feature-icon mb-3">
                    <i class="icofont-support text-lg"></i>
                  </div>
                   <span class="h3">Call for an Emergency Service!</span>
                    <h2 class="text-color mt-3">+01121664514 </h2>
                </div>
            </div>
      
            <div class="col-lg-8">
                 <div class="appoinment-wrap mt-5 mt-lg-0 pl-lg-5">
                  <h2 class="mb-2 title-color">Book an appoinment</h2>
                     <form id="#" class="appoinment-form" method="post" action="#">
                          <div class="row">
                               <div class="col-lg-6">
                                  <div class="form-group">
                                      <select class="form-control" id="exampleFormControlSelect1">
                                        <option>Choose Department</option>
                                        <option>Orthopedic department</option>
                                        <option>Department of Surgery</option>
                                        <option>Department of Heart</option>
                                        <option>Department of Dantal</option>
                                      </select>
                                  </div>
                              </div>
      
                               <div class="col-lg-6">
                                  <div class="form-group">
                                      <input name="date" id="date" type="text" class="form-control" placeholder="Day/Month">
                                  </div>
                              </div>
       
                               <div class="col-lg-6">
                                  <div class="form-group">
                                      <input name="name" id="name" type="text" class="form-control" placeholder="Full Name">
                                  </div>
                              </div>

                              <div class="col-lg-6">
                                <div class="form-group">
                                    <input name="name" id="name" type="text" class="form-control" placeholder="Age">
                                </div>
                              </div>

                              <div class="col-lg-6">
                                <div class="form-group">
                                    <input name="name" id="name" type="text" class="form-control" placeholder="Gender">
                                </div>
                              </div>
      
                              <div class="col-lg-6">
                                <div class="form-group">
                                    <input name="name" id="name" type="text" class="form-control" placeholder="Phone nuber">
                                </div>
                              </div>
                          </div>
      
                          <a class="btn btn-main btn-round-full" asp-controller="Nurse_ayman" asp-action="Index">Make Appointment<i class="icofont-simple-right ml-2"></i></a>
                      </form>
                  </div>
              </div>
            </div>
          </div>
    </section>
  </section>

      <script>
        function updateDate() {
          var dayDiv = document.getElementById("day");
          var dateDiv = document.getElementById("date");
          var timeDiv = document.getElementById("time");
          var today = new Date();
          var daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
          var dayOfWeek = daysOfWeek[today.getDay()];
          var dateString = today.toLocaleDateString();
          var timeString = today.toLocaleTimeString();
          dayDiv.innerHTML = dayOfWeek;
          dateDiv.innerHTML = dateString;
          timeDiv.innerHTML = timeString;
        }
    
        updateDate(); 
        setInterval(function() {
          updateDate();
        }, 1000);
        
       </script>

Views/Nurse_ayman/Nurse_Cash_Flow.cshtml
@model cash_flow

@{
    ViewBag.Title = "Cash Flow";
    Layout = "_Layout_Nurse_ayman";
}

<link rel="icon" href="~/theme/images/favicon.ico" type="image/icon type" />
<style>

      .date-box {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        justify-content: space-between;
        border: 1px solid #ccc;
        padding: 10px;
        margin: 30px 0px;
        width: 100%;
        font-size: 20px;
        color: #6f8ba4;
        background-color: #eee;
        cursor: not-allowed;
      }
      .date-item {
        text-align: center;
      }
    
      .date-item-label {
        font-weight: bold;
      }
    
      .income-box {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        justify-content: space-between;
        border: 1px solid #ccc;
        padding: 10px;
        margin: 10px 0px;
        width: 100%;
        font-size: 20px;
        color: #6f8ba4;
        background-color: #eee;
        cursor: not-allowed;
      }
    
      .income-item {
        text-align: center;
      }
    
      .income-item-label {
        font-weight: bold;
      }
    
      .income-value {
        font-size: 30px;
        margin-top: 20px;
      }
    
      .disabled {
        opacity: 0.8;
        pointer-events: none;
      }
    
      .total-income {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 30px;
        padding: 20px;
        font-size: 50px;
        text-align: center;
        color: #fff;
        background-color: #007bff;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        transform: translatey(0%);
        z-index: 1;
      }
    
      .total-income::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: linear-gradient(to bottom right, #007bff, #00c0ff);
        opacity: 0.8;
        z-index: -1;
      }
    </style>
    
    <section class="a-page-title bg-1"> 
      <div class="overlay"></div>
        <div class="column-md">
          <div class="text-center">
            <h1 class="text-capitalize">Hospital Management System</h1>
            <ul class="line-in-list">
              <li class="nurse-list"><a asp-controller="Nurse_ayman" asp-action="Index" asp-route-id="@ViewBag.ID" class="except"> Nurse</a></li>
              <li class="nurse-list">/</li>
              <li class="nurse-list">Nurse - Cash Flow</li>
            </ul>
          </div>
        </div>
    </section>

    <section class="Nurse-Cash-flow-section">

        <div class="date-box" id="date-box" disabled>
            <div class="date-item">
              <div class="date-item-label">Day</div>
              <div id="day"></div>
            </div>
            <div class="date-item">
              <div class="date-item-label">Date</div>
              <div id="date"></div>
            </div>
            <div class="date-item">
              <div class="date-item-label">Time</div>
              <div id="time"></div>
            </div>
        </div>


        <div class="income-box disabled">
            <div class="income-item">
              <div class="income-item-label">Appointment Income</div>
              <div class="income-value" id="appointment-income"></div>
            </div>
            <div class="income-item">
              <div class="income-item-label">Pharmacy Income</div>
              <div class="income-value" id="pharmacy-income"></div>
            </div>
            <div class="income-item">
              <div class="income-item-label">Lab Income</div>
              <div class="income-value" id="lab-income"></div>
            </div>
          </div>
          <div class="total-income" id="total-income"></div>
        
        
    </section>


    <script>
      function updateDate() {
        const dayDiv = document.getElementById("day");
        const dateDiv = document.getElementById("date");
        const timeDiv = document.getElementById("time");
        const today = new Date();
        const daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        const dayOfWeek = daysOfWeek[today.getDay()];
        const dateString = today.toLocaleDateString();
        const timeString = today.toLocaleTimeString();
        dayDiv.innerHTML = dayOfWeek;
        dateDiv.innerHTML = dateString;
        timeDiv.innerHTML = timeString;
      }
  
      updateDate(); // initial call to display current date and time
  
      // update date and time every second
      setInterval(function() {
        updateDate();
      }, 1000);
    </script>
  
  <script>
      const appointmentIncome = @Model.appointments_cash;
      const pharmacyIncome = @Model.Pharmacy_cash;
      const labIncome = @Model.Lab_cash ;
  
      function displayIncome() {
        const appointmentIncomeDiv = document.getElementById("appointment-income");
        const pharmacyIncomeDiv = document.getElementById("pharmacy-income");
        const labIncomeDiv = document.getElementById("lab-income");
        const totalIncomeDiv = document.getElementById("total-income");
  
        const totalIncome = appointmentIncome + pharmacyIncome + labIncome;
  
        appointmentIncomeDiv.innerHTML = "$" + appointmentIncome.toLocaleString();
        pharmacyIncomeDiv.innerHTML = "$" + pharmacyIncome.toLocaleString();
        labIncomeDiv.innerHTML = "$" + labIncome.toLocaleString();
        totalIncomeDiv.innerHTML = "$" + totalIncome.toLocaleString();
      }
  
      displayIncome(); // initial call to display current incomes
    </script>

Views/Nurse_ayman/Nurse_add_new.cshtml
@model dynamic

@{
    ViewBag.Title = "Nurse Add New Patient";
    Layout = "_Layout_Nurse_ayman";
}

<section class="a-page-title bg-1"> 
    <div class="overlay"></div>
    <div class="column-md">
        <div class="text-center">
            <h1 class="text-capitalize">Hospital Management System</h1>
            <ul class="line-in-list">
                <li class="nurse-list"><a asp-controller="Nurse_ayman" asp-action="Index" class="except"> Nurse</a></li>
                <li class="nurse-list">/</li>
                <li class="nurse-list">Nurse - Add New Patient </li>
            </ul>
        </div>
    </div>
</section>
    
<section class="Nurse-Find-section">

    <div class="date-box" id="date-box" disabled>
        <div class="date-item">
            <div class="date-item-label">Day</div>
            <div id="day"></div>
        </div>
        <div class="date-item">
            <div class="date-item-label">Date</div>
            <div id="date"></div>
        </div>
        <div class="date-item">
            <div class="date-item-label">Time</div>
            <div id="time"></div>
        </div>
    </div>

    <h3 style="color: #6f8ba4; margin: 10px 20px;">Add New Patient</h3>



</section>

<script>
    function updateDate() {
      const dayDiv = document.getElementById("day");
      const dateDiv = document.getElementById("date");
      const timeDiv = document.getElementById("time");
      const today = new Date();
      const daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      const dayOfWeek = daysOfWeek[today.getDay()];
      const dateString = today.toLocaleDateString();
      const timeString = today.toLocaleTimeString();
      dayDiv.innerHTML = dayOfWeek;
      dateDiv.innerHTML = dateString;
      timeDiv.innerHTML = timeString;
    }

    updateDate(); 
    setInterval(function() {
      updateDate();
    }, 1000);
    
   </script>